#!/bin/bash
ACTION=$1
CONTAINER_IP=$2
CONTAINER_PORT=$3
HOST_PORT=$4

if [[ $# -lt 2 ]] || [[ "$1" == "-h" ]]; then
    echo "Help:"
    echo ""
    echo "command:"
    echo "    forward-ip [action] [container ip] [container port] "
    echo ""
    echo "Example: "
    echo "    forward-ip add 172.18.251.2 80 8080"
    echo "    forward-ip del 172.18.251.2 80 8080"
    exit 0
fi

ip1=$(echo $CONTAINER_IP | cut -d "." -f 1)
ip2=$(echo $CONTAINER_IP | cut -d "." -f 2)
ip16=$ip1.$ip2
INTERFACE=$(ip a | grep -v kube | grep -v docker | grep -vw '127.0.0.1' | grep inet | grep -v inet6 | sed 's/\//\ /g' | grep ${ip16} | awk '{print $NF}')

if [ "${ACTION}" == "add" ]; then
    ACTION=A
elif [ "${ACTION}" == "del" ]; then   
    ACTION=D
elif [ "${ACTION}" == "get" ]; then    
    echo ""
else
    echo "unsupported action $1"
    exit -1    
fi

if [ "${HOST_PORT}" == "" ]; then
    HOST_PORT=${CONTAINER_PORT}
fi

if [ "${ACTION}" != "get" ]; then    
    iptables -t nat -${ACTION} POSTROUTING --source ${CONTAINER_IP} --destination ${CONTAINER_IP} -p tcp --dport ${HOST_PORT} -j MASQUERADE
    iptables -t nat -${ACTION} DOCKER ! -i ${INTERFACE} --source 0.0.0.0/0 --destination 0.0.0.0/0 -p tcp --dport ${HOST_PORT}  -j DNAT --to ${CONTAINER_IP}:${CONTAINER_PORT}
    iptables -${ACTION} DOCKER ! -i ${INTERFACE} -o ${INTERFACE} --source 0.0.0.0/0 --destination ${CONTAINER_IP} -p tcp --dport ${CONTAINER_PORT} -j ACCEPT
fi

# iptables -t nat -nvL --line-number | grep MASQUERADE | grep ${HOST_PORT} | grep ${CONTAINER_IP}
# iptables -t nat -nvL --line-number | grep "${CONTAINER_IP}:${CONTAINER_PORT}"

iptables -t nat -S POSTROUTING | grep ${CONTAINER_IP}
iptables -t nat -S DOCKER | grep ${CONTAINER_IP}
iptables -S DOCKER| grep ${CONTAINER_IP}