#!/bin/bash 

#####################################
#
# Set up two kind clusters:
#   1. a management plane which will have a service-mesh-hub namespace, and
#   2. a target cluster
#
# The management plane will have the appropriate secret for communicating with the target cluster
# Your kube context will be left pointing to the management plane cluster
# The target cluster will have Istio set up in the istio-system namespace in its demo profile
#
# To clean up **ALL** of your kind clusters, run this script as: `bash ci/setup-kind.sh cleanup`
# I had some trouble with the docker VM running out of disk space- run this cleanup step often if you can
#
#####################################

if [ "$1" == "-h" ]; then 
echo "Command line help:"
echo ""
echo "./install [cluster number or cluster name (Optional)] [api-server port number (Optional)]"
echo ""
echo "Examples:"
echo "1. Default:"
echo "Optional:"
echo "   ./install "
echo "   ./install 1"
echo "   ./install cluster1"
echo "   ./install cluster1 6441"
exit 0
fi


export COLOR_PREFIX="\e"
export ECHO_E="echo -e"
if [ "$OS" == "Darwin" ]; then
    export COLOR_PREFIX="\033"
fi

export DARKRED="\033[1;31m"
export RED="\033[3;31m"
export DARKGREEN="\033[1;32m"
export GREEN="\033[3;32m"
export DARKYELLOW="\033[1;33m"
export YELLOW="\033[3;33m"
export DARKBLUE="\033[1;34m"
export BLUE="\033[3;34m"
export DARKPURPLE="\033[1;35m"
export PURPLE="\033[3;35m"
export DARKTEAL="\033[1;36m"
export TEAL="\033[3;36m"
export DARKGRAY="\033[1;90m"
export GRAY="\033[3;37m"
export ENDCOLOR="\033[3;0m"
export CANYON=${TEAL}

export E_DARKRED="${COLOR_PREFIX}[1;31m"
export E_RED="${COLOR_PREFIX}[3;31m"
export E_DARKGREEN="${COLOR_PREFIX}[1;32m"
export E_GREEN="${COLOR_PREFIX}[3;32m"
export E_DARKYELLOW="${COLOR_PREFIX}[1;33m"
export E_YELLOW="${COLOR_PREFIX}[3;33m"
export E_DARKBLUE="${COLOR_PREFIX}[1;34m"
export E_BLUE="${COLOR_PREFIX}[3;34m"
export E_DARKPURPLE="${COLOR_PREFIX}[1;35m"
export E_PURPLE="${COLOR_PREFIX}[3;35m"
export E_DARKTEAL="${COLOR_PREFIX}[1;36m"
export E_TEAL="${COLOR_PREFIX}[3;36m"
export E_ENDCOLOR="${COLOR_PREFIX}[3;0m"

WORKSPACE=${PWD}

export KUBECONFIG=~/.kube/config
export PATH=$PATH:${WORKSPACE}/bin

status=1
spin="/-\|"

# prerequisites


cluster_num=$(kind get clusters | wc -l)
if [[ $((cluster_num)) > 0 ]]; then
  $ECHO_E "${GREEN}List all KinD clusters: ${E_GREEN}" 
  echo ""
  kind get clusters
  echo ""
  $ECHO_E "${RED}Do you want to delete above KinD clusters? $E_RED"
  
  while true; do
    read -p "Type 'Y' to delete them all, or 'N' to skip: " yn 
    case $yn in
      [Yy]* ) break;;
      [Nn]* ) exit 0;;
      * ) echo "" ; echo "Please answer yes or no." ;;
    esac
  done    
  kind get clusters | while read -r r; do kind delete cluster --name $r; done
fi

echo -e "${GREEN}✔${E_GREEN}  All KinD clusters are removed"
